### ISSUE TITLE
Finding Patterns algorithm related

### ISSUE THREAD

**Issue by suds2005** [hieplpvip/cses-solutions#1]
Hi,

Can you point me the algorithm and its explanation used in this code. I basically tried with KMP but the program encountered TLE. Figured out that the no of patterns (and thereby its pre-processing) is more than the text itself.

Please let me know.

Sincerely,
Suds

**Comment by hieplpvip** [comment]
Hi,

The data structure used is Suffix Automaton. You can read about it [here](https://cp-algorithms.com/string/suffix-automaton.html). It's basically a trie of all suffixes but much more compact. It requires linear memory and can be built in linear time complexity.

**Comment by hieplpvip** [comment]
These are the problems that can be solved with Suffix Automaton:
- Finding Patterns
- Counting Patterns
- Pattern Positions
- Distinct Substrings
- Repeating Substring
- Substring Order I
- Substring Order II
- Substring Distribution

I suggest solving all of them to (kinda) master Suffix Automaton.

**Comment by suds2005** [comment]
Sincere thanks. Awesome.


Sincerely,
Sudarsan.D

     On Tuesday, 22 June, 2021, 02:01:15 pm IST, Bao-Hiep Le ***@***.***> wrote:  
 
 


Hi,

The data structure used is Suffix Automaton. You can read about it here. It's basically a trie of all suffixes but much more compact. It requires linear memory and can be built in linear time complexity.
