### ISSUE TITLE
Distinct Routes

### ISSUE THREAD

**Issue by suds2005** [hieplpvip/cses-solutions#2]
Hi,

I am trying to figure out why a BFS + DFS is done for "Distinct routes".
I kind of have a sense, but not clear.

For example the graph is like this
1 2
1 3
3 2
2 4
4 5
Here the paths are 1 2 4 5/1 3 5. 

However in a different examplee going at the same level (like between 3 and 2)  cann cause problems. For example if we traverse from 1 to  3 and  then 3 to 2 and figure out a way. It can mean that we cannot take the path from 1 to 3 again (the teleporter is used). So in some cases
we need to traverse in the same level, or in some cases we cannot.

How do we distinguish?
 1 2
1 6
1 8
8 2
8 7
7 9
2 9
2 6
6 9
Here if we take 1 2 6 9 as first path then 1 8 2 9 or 1 8 7 9 is the other path. But this is wrong as
there are 3 paths possible 1 2 9  1 6 9 1 87 9

Any thoughts??

a) Why cannot we simply do DFS from the root node?

**Comment by hieplpvip** [comment]
It's actually Dinitz algorithm. You can read more about it [here](https://cp-algorithms.com/graph/dinic.html)
